spring.application.name=Count-it
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://abhi:manager1@count.4kyhw.mongodb.net/?retryWrites=true&w=majority
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.database=users_db
