export const inventoryTable =[
    {
        id: 1,
        product:"mouse",
        price : 200,
        amount : 50,
        date: "30-02-500",
        status: "avialable",
    },
    {
        id: 2,
        product:"keybord",
        price : 300,
        amount : 40,
        date: "03-05-1300",
        status: "out-of-stock",
    },
    {
        id: 3,
        product:"maruti 800",
        price : 2100000,
        amount : 5,
        date: "01-01-900",
        status: "avialable",
    },
    {
        id: 4,
        product:"sabun",
        price : 20,
        amount : 100,
        date: "11-09-2000",
        status: "khtm ho gaye",
    },
    {
        id: 5,
        product:"monitor",
        price : 1500,
        amount : 35,
        date: "02-04-2004",
        status: "avialable",
    },
    {
        id: 6,
        product:"jgohg",
        price : 400,
        amount : 1,
        date: "08-05-2003",
        status: "avialable",
    },
]